### PR TITLE
Fixes issue #21 by checking the ref received by the GitHub API on push event

### LINKED ISSUE #21: Checkout specific code according to assignment, not just clone main
https://www.eclipse.org/forums/index.php/t/1065371/

### PR DESCRIPTION
**Pull request by emilmyresten**
Also implements helperfunction + test, as well as new folder hierarchy to keep track of builds on specific branch.
 new structure is /builds/<branch>/<repo+dateTime>
This change does not affect log parsing functionality.

### CODE REVIEW

File: src/test/java/group8/UtilitiesTest.java [hunk 1]
```diff
@@ -65,4 +65,14 @@ public void requestBodyAsStringInvalidTest() throws IOException {
...
 
+    @Test
+    public void getRefSuffixValidTest() {
+        Assert.assertEquals("issue1", Utilities.getRefSuffix("refs/heads/issue/1"));
+    }
+
+    @Test
+    public void getRefSuffixInvalidTest() {
+        Assert.assertEquals("containsNoSlashes", Utilities.getRefSuffix("containsNoSlashes"));
+    }
```
Comment (SimonOsnes) [inline src/test/java/group8/UtilitiesTest.java:76]: If this is an invalid test, shouldn't it asserNotEquals (if that is a thing)? I feel like this test and the one before does the same thing

**Review by SimonOsnes — APPROVED** [review]
One small thing regarding the test, but the code looks really good!

**Review by joakim-olsson — APPROVED** [review]
LGTM
